# Generated by Django 4.1.7 on 2023-04-29 12:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('remaining_budget', models.FloatField()),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_benefit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('relative_penalty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('total_value', models.IntegerField()),
                ('relative_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('relative_risk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('value_percentage', models.FloatField(blank=True, null=True)),
                ('cost_percentage', models.FloatField()),
                ('risk_percentage', models.FloatField()),
                ('priority', models.FloatField()),
                ('status', models.TextField(default='Pending', max_length=20)),
                ('type', models.TextField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('feature_score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.feature_score')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feasibility', models.FloatField()),
                ('market_value', models.FloatField()),
                ('cost_efective', models.FloatField()),
                ('risk', models.FloatField()),
                ('originaity', models.FloatField()),
                ('value_proposition', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.TextField(max_length=50)),
                ('task_description', models.TextField()),
                ('tag', models.TextField(max_length=30)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ideas.features')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('problem_to_solve', models.TextField(null=True)),
                ('progress', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ideas.budget')),
                ('features', models.ManyToManyField(to='Ideas.features')),
                ('files', models.ManyToManyField(to='Ideas.files')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='Ideas.tags')),
                ('tasks', models.ManyToManyField(to='Ideas.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('problem_to_solve', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(to='Ideas.features')),
                ('files', models.ManyToManyField(to='Ideas.files')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.score')),
                ('tags', models.ManyToManyField(to='Ideas.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Archived_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('problem_to_solve', models.TextField(null=True)),
                ('progress', models.FloatField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.features')),
                ('files', models.ManyToManyField(to='Ideas.files')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_was', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='Ideas.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Archived_Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('problem_to_solve', models.TextField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(to='Ideas.files')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.score')),
                ('tags', models.ManyToManyField(to='Ideas.tags')),
            ],
        ),
    ]
