# Generated by Django 4.1.7 on 2024-01-31 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ideas.features'),
        ),
        migrations.AddField(
            model_name='score',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.ideas'),
        ),
        migrations.AddField(
            model_name='projects',
            name='assignee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ideas.budget'),
        ),
        migrations.AddField(
            model_name='projects',
            name='features',
            field=models.ManyToManyField(to='Ideas.features'),
        ),
        migrations.AddField(
            model_name='projects',
            name='files',
            field=models.ManyToManyField(to='Ideas.files'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='Ideas.tags'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.ManyToManyField(to='Ideas.tasks'),
        ),
        migrations.AddField(
            model_name='ideas',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideas',
            name='features',
            field=models.ManyToManyField(to='Ideas.features'),
        ),
        migrations.AddField(
            model_name='ideas',
            name='files',
            field=models.ManyToManyField(to='Ideas.files'),
        ),
        migrations.AddField(
            model_name='ideas',
            name='tags',
            field=models.ManyToManyField(to='Ideas.tags'),
        ),
        migrations.AddField(
            model_name='files',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='features',
            name='feature_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.feature_score'),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archived_projects',
            name='assignee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archived_projects',
            name='features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.features'),
        ),
        migrations.AddField(
            model_name='archived_projects',
            name='files',
            field=models.ManyToManyField(to='Ideas.files'),
        ),
        migrations.AddField(
            model_name='archived_projects',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_was', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archived_projects',
            name='tags',
            field=models.ManyToManyField(to='Ideas.tags'),
        ),
        migrations.AddField(
            model_name='archived_ideas',
            name='files',
            field=models.ManyToManyField(to='Ideas.files'),
        ),
        migrations.AddField(
            model_name='archived_ideas',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.score'),
        ),
        migrations.AddField(
            model_name='archived_ideas',
            name='tags',
            field=models.ManyToManyField(to='Ideas.tags'),
        ),
    ]
