# Generated by Django 4.2 on 2024-02-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0003_feature_score_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature_score',
            name='employee',
        ),
    ]
