# Generated by Django 4.1.7 on 2023-04-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ideas', '0003_alter_feature_score_relative_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideas',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ideas',
            name='features',
            field=models.ManyToManyField(to='Ideas.features'),
        ),
        migrations.AddField(
            model_name='projects',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.ManyToManyField(to='Ideas.tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.feature_score'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.score'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='features',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Archived_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('problem_to_solve', models.TextField(null=True)),
                ('progress', models.FloatField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.features')),
                ('files', models.ManyToManyField(to='Ideas.files')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_was', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='Ideas.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Archived_Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('problem_to_solve', models.TextField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(to='Ideas.files')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.score')),
                ('tags', models.ManyToManyField(to='Ideas.tags')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='features',
            field=models.ManyToManyField(to='Ideas.features'),
        ),
    ]
