# Generated by Django 4.2 on 2024-02-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0005_feature_score_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='feature_score',
            field=models.FloatField(null=True),
        ),
    ]
