# Generated by Django 4.2 on 2024-02-01 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ideas', '0006_alter_features_feature_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_benefit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('relative_penalty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('total_value', models.IntegerField()),
                ('relative_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('relative_risk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('priority', models.FloatField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='features',
            name='cost_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='priority',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='risk_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Feature_Score',
        ),
        migrations.AlterField(
            model_name='features',
            name='feature_score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.featurescore'),
        ),
    ]
