# Generated by Django 4.2 on 2024-02-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0009_rename_cost_efective_score_cost_effective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
