# Generated by Django 4.2 on 2024-02-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0010_score_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
